### PR TITLE
approval keyword

### PR DESCRIPTION
**Pull request by Ewa-Tokarz**

### CODE REVIEW

**Comment by trstringer** [comment]
Thank you for your contribution! While this PR adds the necessary test to add a new word, it also needs to include the new word in `constants.go` in the `approvedWords` slice.

**Comment by trstringer** [comment]
And also once you add this word in the slice, can you add it in the documentation as well? Thanks!

**Comment by Bwvolleyball** [comment]
Just going to throw it out there that this could also be solved by https://github.com/trstringer/manual-approval/pull/66, and this could just be a new custom approval word.

**Comment by trstringer** [comment]
Agreed, closing this as it is fixed in #66.

**Pull request closed without merging**
