### PR TITLE
Add new input 'issue-body'

### PR DESCRIPTION
**Pull request by gonzolino**
Similar to the 'issue-title' input, 'issue-body' allows to put custom text to
the body of the approval issue.

`make lint` and `make build` are working, but I do not know how to further test
this... So any help in testing this change is much appreciated.

This might fix issues #69 and #49.

### CODE REVIEW

**Comment by trstringer** [comment]
Thank you for your contribution! I will review this PR shortly.

**Comment by gonzolino** [comment]
Hey @trstringer, any updates on the review? :)

**Comment by trstringer** [comment]
Thank you for your contribution!

**Comment by roi-zentner** [comment]
@trstringer This has been merged but doesn't look like it is available.
I am getting: `Unexpected input(s) 'issue-body'`.
Please advise 🙏

**Comment by greg-douglas-audiens** [comment]
I believe we require a new docker image to be published before we can start using `issue-body`.

**Pull request merged**
